modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/ultimate-plane-mod/issues"
[[mods]]
modId = "plane"
version = "${mod_version}"
displayName = "Ultimate Plane Mod"
updateJSONURL = "https://update.maxhenkel.de/forge/plane"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ultimate-plane-mod"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''Planes in Minecraft'''
[[dependencies.plane]]
modId = "forge"
mandatory = true
versionRange = "${forge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.plane]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.plane]]
modId = "car"
mandatory = true
versionRange = "${car_dependency}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.plane]]
modId = "jade"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"